# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-17 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollblockchain',
            name='timeStampVote',
            field=models.CharField(max_length=64),
        ),
    ]
