# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-17 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180217_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollblockchain',
            name='nonce',
            field=models.CharField(max_length=64),
        ),
    ]
